apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: syv1j7wf3-java-springboot 
  janus-idp.io/tekton: syv1j7wf3-java-springboot
  backstage.io/kubernetes-id: syv1j7wf3-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: syv1j7wf3-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml